# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{idclight}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Preston Lee"]
  s.date = %q{2010-05-11}
  s.description = %q{A Ruby gem for accessing the freely available IDClight (IDConverter Light) web service, which convert between different types of gene IDs such as Hugo and Entrez. Queries are screen scraped from http://idclight.bioinfo.cnio.es.}
  s.email = %q{conmotto@gmail.com}
  s.executables = ["convert.rb", "ensembl_to_entrez.rb", "ensembl_to_hugo.rb", "hugo_to_ensembl.rb", "hugo_to_entrez.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".project",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/convert.rb",
     "bin/ensembl_to_entrez.rb",
     "bin/ensembl_to_hugo.rb",
     "bin/hugo_to_ensembl.rb",
     "bin/hugo_to_entrez.rb",
     "idclight.gemspec",
     "lib/idclight.rb",
     "test/helper.rb",
     "test/test_idclight.rb"
  ]
  s.homepage = %q{http://github.com/preston/idclight}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby programmnig interface to the IDCLight online database.}
  s.test_files = [
    "test/helper.rb",
     "test/test_idclight.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<hpricot>, [">= 0.8"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<hpricot>, [">= 0.8"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<hpricot>, [">= 0.8"])
  end
end

