# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "idclight"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Preston Lee"]
  s.date = "2012-04-12"
  s.description = "A Ruby gem for accessing the freely available IDClight (IDConverter Light) web service, which convert between different types of gene IDs such as Hugo and Entrez. Queries are screen scraped from http://idclight.bioinfo.cnio.es."
  s.email = "conmotto@gmail.com"
  s.executables = ["ensembl_to_entrez.rb", "ensembl_to_hugo.rb", "hugo_to_ensembl.rb", "hugo_to_entrez.rb", "idclight_convert.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".project",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/ensembl_to_entrez.rb",
    "bin/ensembl_to_hugo.rb",
    "bin/hugo_to_ensembl.rb",
    "bin/hugo_to_entrez.rb",
    "bin/idclight_convert.rb",
    "idclight.gemspec",
    "lib/idclight.rb",
    "test/helper.rb",
    "test/test_idclight.rb"
  ]
  s.homepage = "http://github.com/tgen/idclight"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.21"
  s.summary = "Ruby programmnig interface to the IDCLight online database."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hpricot>, [">= 0.8"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<hpricot>, [">= 0.8"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<hpricot>, [">= 0.8"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

